### ISSUE TITLE
Notify 3 times

### ISSUE THREAD

**Issue by vmagalhaes** [LenonLopez/angular-notice#5]
HI,

I'm trying to use the method notify 3 times together every 5 minutes, but it just notify the last instance e and another 2 doesn't display the notification.

What can I do?

Thanks

**Comment by LenonLopez** [comment]
@vmagalhaes  can you post a snippet of how you're calling the notify method?  I have an idea, but want to verify what options you are passing into the notify method first.

**Comment by LenonLopez** [comment]
Considering the lack of response, I am going to assume you have resolved your question and therefore will close this issue.
