### ISSUE TITLE
Error when trying to compile

### ISSUE THREAD

**Issue by lucasdp** [LenonLopez/angular-notice#6]
Whenever I try to compile I get:

`/node_modules/angular-notice/lib/native-notification.service.d.ts (11,42): Cannot find name 'NotificationPermission'.`

**Comment by LenonLopez** [comment]
Hello @lucasdp ! Can you please post your app module, app component, as well as the component in which you are using the service?

**Comment by LenonLopez** [comment]
Considering the lack of response, I am going to assume you have resolved your question and therefore will close this issue.
