### ISSUE TITLE
ERROR in vendor.3b702a441f85d9d70088.bundle.js from UglifyJs

### ISSUE THREAD

**Issue by SunilRumbaLama** [LenonLopez/angular-notice#8]
Hi, i am getting a build error in angular-notice. 
It throws an error as following:

`Unexpected token: name (NotificationsModule) [vendor.3b702a441f85d9d70088.bundle.js:62799,6]`

**Comment by LenonLopez** [comment]
@SunilRumbaLama  Thank you for opening an issue. Can you give me more details? For example, how are you including it into your app, etc.

**Comment by LenonLopez** [comment]
closing for lack of response.
